from pydantic import BaseModel, EmailStr, HttpUrl
from typing import List, Optional
from datetime import datetime

# --- COMMENT SCHEMAS ---

class CommentBase(BaseModel):
    content: str

class CommentCreate(CommentBase):
    post_id: int

class Comment(CommentBase):
    id: int
    user_id: int
    post_id: int
    timestamp: datetime
    username: str # We include this so the frontend can show "@Alex"

    class Config:
        from_attributes = True


# --- POST (NEWS) SCHEMAS ---

class PostBase(BaseModel):
    headline: str
    image_url: str
    category: str
    bullet_points: List[str] # List of 3 strings generated by AI
    source_url: Optional[HttpUrl] = None

class PostCreate(PostBase):
    pass

class Post(PostBase):
    id: int
    
    class Config:
        from_attributes = True


# --- USER SCHEMAS ---

class UserBase(BaseModel):
    username: str
    email: EmailStr

class UserCreate(UserBase):
    password: str # Only used when signing up

class User(UserBase):
    id: int
    is_active: bool

    class Config:
        from_attributes = True # Allows Pydantic to read SQLAlchemy models


# --- AUTH SCHEMAS ---

class Token(BaseModel):
    access_token: str
    token_type: str

class TokenData(BaseModel):
    username: Optional[str] = None
